version: '3.4'

services:
  birthmicroservice:
    container_name: "birthmicroservice"
    image: ${DOCKER_REGISTRY-}birthmicroservice
    build:
      context: .
      dockerfile: BirthMicroservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=madison
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx

    volumes:
      - ./conf.d/https/:/https/
    networks:
      - my-network

  apigateway:
    container_name: "apigateway"
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=madison
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    ports:
      - "80:80"

    volumes:
      - ./conf.d/https/:/https/
    networks:
      - my-network

networks:
  my-network:
    external: true
